name: fashion_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  video_player: ^2.4.7
  google_fonts: ^3.0.1
  url_launcher: ^6.1.6
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  fluttertoast: ^8.1.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/ 
   - assets/videos/